<?php
    include "connect_sql.php";
    include "SQLRelative.php";

    if (isset($_POST["id"])) {
        $id = $_POST["id"];
        $tablename = "beta";
        $beta_data = GetProductInfo($servername, $username, $password, $db_name, $tablename, $id);
        $tablename = "preprocess";
        $prep_data = GetProductInfo($servername, $username, $password, $db_name, $tablename, $id);
        // var_dump($beta_data); die();
        // var_dump($prep_data); die();
        $tab1  = "<div class='tab-pane fade show active' id='main' role='tabpanel' aria-labelledby='main-tab'>";
        $tab1 .= "<form>";
        $tab1 .= "    <div class='form-row'>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>廠商名稱</label>";
        $tab1 .= "            <input type='text' class='form-control' id='company_name' name='company_name' value='$prep_data[10]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>商品名稱</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_name' name='product_name' value='$prep_data[1]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>商品價格</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_price' name='product_price' value='$prep_data[2]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>上架數量</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_quantity' name='product_quantity' value='$prep_data[3]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>商品簡介</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_info' name='product_info' value='$prep_data[4]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>商品重量</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_weight' name='product_weight' value='$prep_data[5]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>商品標籤</label>";
        $tab1 .= "            <input type='text' class='form-control' id='product_tag' name='product_tag' value='$prep_data[6]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "        <div class='form-group col-sm-6'>";
        $tab1 .= "            <label for='company_name'>減碳量</label>";
        $tab1 .= "            <input type='text' class='form-control' id='reduceC' name='reduceC' value='$prep_data[8]' readonly>";
        $tab1 .= "        </div>";
        $tab1 .= "    </div>";
        $tab1 .= "</form>";
        $tab1 .= "</div>";

        $tab2  = "<div class='tab-pane fade' id='materialla' role='tabpanel' aria-labelledby='material-tab'>";
        $tab2 .= "<form>";
        $tab2 .= "    <div class='form-row'>";
        $tab2 .= "        <h3 class='col-md-12'>原料一</h3>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Material1'>原料名</label>";
        $tab2 .= "            <input type='text' class='form-control' id='Material1' name='Material1' value='$beta_data[4]' readonly>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Electric1'>開採時用電</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Electric1' name='Electric1' value='$beta_data[5]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Process1_1'>初步加工</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Process1_1' name='Process1_1' value='$beta_data[6]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Process1_2'>進一步加工</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Process1_2' name='Process1_2' value='$beta_data[7]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Mileage1'>總運送里程</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Mileage1' name='Mileage1' value='$beta_data[8]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>km</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Gasoline1'>平均油耗</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Gasoline1' name='Gasoline1' value='$beta_data[9]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>km/L</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "    </div>";
        $tab2 .= "    <hr>";
        $tab2 .= "    <div class='form-row'>";
        $tab2 .= "        <h3 class='col-md-12'>原料二</h3>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Material2'>原料名</label>";
        $tab2 .= "            <input type='text' class='form-control' id='Material2' name='Material2' value='$beta_data[10]' readonly>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Electric2'>開採時用電</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Electric2' name='Electric2' value='$beta_data[11]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                        <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Process2_1'>初步加工</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Process2_1' name='Process2_1' value='$beta_data[12]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Process2_2'>進一步加工</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <div class='input-group-prepend'>";
        $tab2 .= "                    <span class='input-group-text'>每kg</span>";
        $tab2 .= "                </div>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Process2_2' name='Process2_2' value='$beta_data[13]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>度</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Mileage2'>總運送里程</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Mileage2' name='Mileage2' value='$beta_data[14]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>km</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "        <div class='form-group col-md-6'>";
        $tab2 .= "            <label for='Gasoline2'>平均油耗</label>";
        $tab2 .= "            <div class='input-group'>";
        $tab2 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Gasoline2' name='Gasoline2' value='$beta_data[15]' readonly>";
        $tab2 .= "                <div class='input-group-append'>";
        $tab2 .= "                    <span class='input-group-text'>km/L</span>";
        $tab2 .= "                </div>";
        $tab2 .= "            </div>";
        $tab2 .= "        </div>";
        $tab2 .= "    </div>";
        $tab2 .= "</form>";
        $tab2 .= "</div>";

        $tab3  = "<div class='tab-pane fade' id='made' role='tabpanel' aria-labelledby='made-tab'>";
        $tab3 .= "<form>";
        $tab3 .= "    <div class='form-row'>";
        $tab3 .= "        <h3 class='col-md-12'>產品製作</h3>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "            <label for='Mweight1'>原料一</label>";
        $tab3 .= "            <div class='input-group'>";
        $tab3 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Mweight1' name='Mweight1' value='$beta_data[16]' readonly>";
        $tab3 .= "                <div class='input-group-append'>";
        $tab3 .= "                    <span class='input-group-text'>kg</span>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        </div>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "            <label for='Mweight2'>原料二</label>";
        $tab3 .= "            <div class='input-group'>";
        $tab3 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Mweight2' name='Mweight2' value='$beta_data[17]' readonly>";
        $tab3 .= "                <div class='input-group-append'>";
        $tab3 .= "                    <span class='input-group-text'>kg</span>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        </div>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "            <label for='MElec'>製作時耗電</label>";
        $tab3 .= "            <div class='input-group'>";
        $tab3 .= "                <div class='input-group-prepend'>";
        $tab3 .= "                    <span class='input-group-text'>每個</span>";
        $tab3 .= "                </div>";
        $tab3 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='MElec' name='MElec' value='$beta_data[18]' readonly>";
        $tab3 .= "                <div class='input-group-append'>";
        $tab3 .= "                    <span class='input-group-text'>度</span>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        </div>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "            <label for='MWeight'>總重</label>";
        $tab3 .= "            <div class='input-group'>";
        $tab3 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='MWeight' name='MWeight' value='$beta_data[19]' readonly>";
        $tab3 .= "                <div class='input-group-append'>";
        $tab3 .= "                    <span class='input-group-text'>kg</span>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        </div>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "                <label for='Expiration'>使用年限</label>";
        $tab3 .= "                <div class='input-group'>";
        $tab3 .= "                    <input type='number' step='0.001' min='0' max='1000' class='form-control' id='Expiration' name='Expiration' value='$beta_data[20]' readonly>";
        $tab3 .= "                    <div class='input-group-append'>";
        $tab3 .= "                        <span class='input-group-text'>年</span>";
        $tab3 .= "                    </div>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        <div class='form-group col-md-6'>";
        $tab3 .= "            <label for='Bamboo'>竹原料</label>";
        $tab3 .= "            <div class='input-group'>";
        $tab3 .= "                <input type='number' step='0.001' min='0' max='9999' class='form-control' id='Bamboo' name='Bamboo' value='$beta_data[21]' readonly>";
        $tab3 .= "                <div class='input-group-append'>";
        $tab3 .= "                    <span class='input-group-text'>kg</span>";
        $tab3 .= "                </div>";
        $tab3 .= "            </div>";
        $tab3 .= "        </div>";
        $tab3 .= "    </div>";
        $tab3 .= "</form>";
        $tab3 .= "</div>";

        $result = $tab1 . $tab2 . $tab3;

        echo $result;
    }